name: 'GitHub Branch Protection Automation'
description: 'Automate and verify branch protection rules across multiple GitHub repositories'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  github_token:
    description: 'GitHub token with repository access'
    required: true
  github_owner:
    description: 'GitHub organization or username'
    required: true
  repositories:
    description: 'Space-separated list of repositories'
    required: true
  verify_only:
    description: 'Only verify protection rules'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_OWNER: ${{ inputs.github_owner }}
    REPOSITORIES: ${{ inputs.repositories }}
    VERIFY_ONLY: ${{ inputs.verify_only }} 