name: 'GitHub Branch Protection Action'
description: 'Automate branch protection rules across repositories'
inputs:
  github_token:
    description: 'GitHub token with repository access'
    required: true
  github_owner:
    description: 'GitHub organization or username'
    required: true
  repos_file:
    description: 'Path to file containing repository names'
    required: false
  repos:
    description: 'Space-separated list of repositories'
    required: false
  verify_only:
    description: 'Only verify protection rules without modifying'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_OWNER: ${{ inputs.github_owner }}
    VERIFY_ONLY: ${{ inputs.verify_only }}
    REPOS_FILE: ${{ inputs.repos_file }}
    REPOS: ${{ inputs.repos }} 