name: Branch Protection Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:
    inputs:
      verify_only:
        description: 'Only verify protection rules'
        type: boolean
        default: true

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Branch Protection
        uses: ./
        env:
          BRANCH_PROTECTION_ACTION: ${{ secrets.BRANCH_PROTECTION_ACTION }}
        with:
          github_token: ${{ secrets.BRANCH_PROTECTION_ACTION }}
          github_owner: ${{ github.repository_owner }}
          repositories: "genai-security-scripts geo-recon Simplehackingscripts"
          verify_only: ${{ github.event.inputs.verify_only }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload protection report
        uses: actions/upload-artifact@v3
        with:
          name: branch-protection-report
          path: reports/
          retention-days: 30 